Admin10: Lista de Departamentos
Admin1: Cadastro Clientes
Admin2: Cadastro Funcionários
Admin3: Cadastro Filiais
Admin4: Adicionar
Admin5: Lista de Funcionários
Admin6: Ir
Admin7: Lista de Profissoes
Admin8: Lista de Treinamentos
Admin9: Cadastro Entregas 
Admin: Área do Administrador
BemVindo: Seja bem vindo ao nosso site!
Cadastro1: Treinamentos Cadastrados:
Cadastro2: Funcionários Cadastrados:
Cadastro3: Profissoes Cadastrados:
Cadastro4: Departamentos Cadastradao:
Cadastro: Preencha os campos.
CadastroBtn: Enviar
Contato10: Digite sua mensagem
Contato11: Enviar
Contato12: Limpar
Contato1: Entre em contato conosco por meio de um dos nossos canais de comunicação e feche negócio com a gente.
Contato2: Nossa central de atendimento funciona de segunda a sexta-feira das 8h às 18h e aos sábados das 8h às 13h.
Contato3: Nome
Contato4: Email
Contato5: Assunto
Contato6: Mensagem
Contato7: Digite seu nome
Contato8: Digite seu email
Contato9: Digite o assunto
Contato: Contato
DeletarBtn: Deletar
Endereco: Endereço:
Entrega: Entregas
Erro1: A página que você digitou não existe ou está fora do ar.
Erro2: Por favor aguarde alguns segundos, você será redirecionado para nossa página principal.
Erro3: Obrigada!
Erro: Desculpe,
Filial: Filiais
Form1: Cliente
Form2: Funcionário
Form3: Administrador
Form4: Tipo
Form: Cadastro de
Funcionario1: Perfil de
Funcionario2: Você está logado como
Funcionario: Área do Funcionário 
Home: Home
Localizacao: Localização
Login1: Área de Login
Login: Acesso Restrito
Logout: Sair
LogoutTxt: Você foi deslogado com sucesso.
MapaSite: Mapa do Site
Mensagem: Mensagem
Navegacao: Navigacao
Perfil1: Perfil de
Perfil2: Login
Perfil3: Senha
Perfil4: Perfil Filial 
Perfil5: Perfil Cliente
Perfil: Perfil do Usuário
Entrar: Entrar
Sucesso: Formulário enviado com sucesso.
TxtAcao: Remover
TxtCargo: Cargo
TxtCidade: Cidade
TxtCliente: Cliente
TxtCnpj: CNPJ
TxtCpf: CPF
TxtContato: Contato
TxtData: Data
TxtEmail: Email
TxtEndereco: Endereço
TxtFuncionario: Funcionario
TxtLogin: Login
TxtNascimento: Data de Nascimento
TxtNome: Nome
TxtSenha: Senha
TxtTelefone: Telefone
Voltar: Voltar