Admin10: Lista de Departamentos
Admin1: Cadastro Clientes
Admin2: Cadastro Funcionários
Admin3: Cadastro Filiais
Admin4: Adicionar
Admin5: Lista de Funcionários
Admin6: Ir
Admin7: Lista de Profissoes
Admin8: Lista de Treinamentos
Admin9: Cadastro Entregas 
Admin: Área do Administrador
BemVindo: Seja bem vindo ao nosso site!
Cadastro1: Treinamentos Cadastrados:
Cadastro2: Funcionários Cadastrados:
Cadastro3: Profissoes Cadastrados:
Cadastro4: Departamentos Cadastradao:
Cadastro: Preencha os campos.
CadastroBtn: Enviar
Contato10: Digite sua mensagem
Contato11: Enviar
Contato12: Limpar
Contato3: Nome
Contato4: Email
Contato5: Assunto
Contato6: Mensagem
Contato: Contato
DeletarBtn: Deletar
Endereco: Endereço:
Entrega: Entregas
Erro1: A página que você digitou não existe ou está fora do ar.
Erro2: Por favor aguarde alguns segundos, você será redirecionado para nossa página principal.
Erro3: Obrigada!
Erro: Desculpe,
MenuQuemSomos1: Quem somos nós
QuemSomos1: A Sistreina é uma empresa comprometida com o crescimento profissional de todos os tralhadores proporcionando uma plataforma de gestão de treinamentos empresarial.
QuemSomos2: Com o objetivo também de se formar na FATEC, Diego, Lauro e Vitor criaram este site como trabalho de conclusão de curso.
MenuNossosServiços1: Nosso Serviços
NossosServiços1: - Base unificada de funcionários;
NossosServiços2: - Gestão de usuários com facilidade;
NossosServiços3: - Criação de treinamentos simplificada;
NossosServiços4: - Relacionamento do funcionário com o treinamento;
NossosServiços5: - Envio de convites;
NossosServiços6: - Aviso de treinamento;
Form1: Cliente
Form2: Funcionário
Form3: Administrador
Form4: Profile
Form: Cadastro de
Funcionario1: Perfil de
Funcionario2: Você está logado como
Funcionario: Área do Funcionário 
Home: Home
Localizacao: Localização
Login1: Área de Login
Login: Acesso Restrito
Logout: Sair
LogoutTxt: Você foi deslogado com sucesso.
MapaSite: Mapa do Site
Mensagem: Mensagem
Navegacao: Navegaço
Perfil: Perfil do Usuário
Entrar: Entrar
Sucesso: Solicitação enviada com sucesso.
TxtAcao: Remover
TxtCargo: Cargo
TxtCidade: Cidade
TxtCliente: Cliente
TxtCnpj: CNPJ
TxtCpf: CPF
TxtContato: Contato
TxtData: Data
TxtEmail: Email
TxtEndereco: Endereço
TxtFuncionario: Funcionario
TxtLogin: Login
TxtNascimento: Data de Nascimento
TxtNome: Nome
TxtSenha: Senha
TxtTelefone: Telefone
Voltar: Voltar
TxtResponsavellbl: Responsável
TxtFuncionariolbl: Funcionário